
// Objective-C API for talking to the following Go packages
//
//	gitlab.33.cn/wallet/walletapi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Walletapi_FRAMEWORK_H__
#define __Walletapi_FRAMEWORK_H__

#include "Walletapi.objc.h"
#include "Universe.objc.h"

#endif
