// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'db_model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:User.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// User TABLE
class TableUser extends SqfEntityTableBase {
  TableUser() {
    // declare properties of EntityTable
    tableName = 'user';
    primaryKeyName = 'account';
    primaryKeyType = PrimaryKeyType.text;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('userName', DbType.text),
      SqfEntityFieldBase('motto', DbType.text),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableUser();
  }
}

// TargetRelation TABLE
class TableTargetRelation extends SqfEntityTableBase {
  TableTargetRelation() {
    // declare properties of EntityTable
    tableName = 'targetRelation';

    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('activeTargetId', DbType.integer,
          isPrimaryKeyField: true, isIndexGroup: 1),
      SqfEntityFieldBase('passiveTargetId', DbType.integer,
          isPrimaryKeyField: true, isIndexGroup: 1),
      SqfEntityFieldBase('name', DbType.text),
      SqfEntityFieldBase('label', DbType.text),
      SqfEntityFieldBase('remark', DbType.text),
      SqfEntityFieldBase('typeName', DbType.text),
      SqfEntityFieldBase('priority', DbType.integer),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableTargetRelation();
  }
}

// Target TABLE
class TableTarget extends SqfEntityTableBase {
  TableTarget() {
    // declare properties of EntityTable
    tableName = 'target';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_unique;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('code', DbType.text),
      SqfEntityFieldBase('name', DbType.text),
      SqfEntityFieldBase('typeName', DbType.text),
      SqfEntityFieldBase('belongId', DbType.integer),
      SqfEntityFieldBase('thingId', DbType.integer),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableTarget();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class DbModel extends SqfEntityModelProvider {
  DbModel() {
    databaseName = dbModel.databaseName;
    password = dbModel.password;
    dbVersion = dbModel.dbVersion;
    preSaveAction = dbModel.preSaveAction;
    logFunction = dbModel.logFunction;
    databaseTables = [
      TableUser.getInstance,
      TableTargetRelation.getInstance,
      TableTarget.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = dbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = dbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region User
class User extends TableBase {
  User({this.account, this.userName, this.motto}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  User.withFields(this.account, this.userName, this.motto) {
    _setDefaultValues();
  }
  User.withId(this.account, this.userName, this.motto) {
    _setDefaultValues();
  }
  // fromMap v2.0
  User.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    account = o['account'].toString();
    if (o['userName'] != null) {
      userName = o['userName'].toString();
    }
    if (o['motto'] != null) {
      motto = o['motto'].toString();
    }

    isSaved = true;
  }
  // FIELDS (User)
  String? account;
  String? userName;
  String? motto;
  bool? isSaved;
  // end FIELDS (User)

  static const bool _softDeleteActivated = false;
  UserManager? __mnUser;

  UserManager get _mnUser {
    return __mnUser = __mnUser ?? UserManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['account'] = account;
    if (userName != null || !forView) {
      map['userName'] = userName;
    }
    if (motto != null || !forView) {
      map['motto'] = motto;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['account'] = account;
    if (userName != null || !forView) {
      map['userName'] = userName;
    }
    if (motto != null || !forView) {
      map['motto'] = motto;
    }

    return map;
  }

  /// This method returns Json String [User]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [User]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [account, userName, motto];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [account, userName, motto];
  }

  static Future<List<User>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR User.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<User>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <User>[];
    try {
      objList = list
          .map((user) => User.fromMap(user as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR User.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<User>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<User> objList = <User>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = User.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns User by ID if exist, otherwise returns null
  /// Primary Keys: String? account
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [User] if exist, otherwise returns null
  Future<User?> getById(String? account,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (account == null) {
      return null;
    }
    User? obj;
    final data = await _mnUser.getById([account]);
    if (data.length != 0) {
      obj = User.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (User) object. If the Primary Key (account) field is null, returns Error.
  /// INSERTS (If not exist) OR REPLACES (If exist) data while Primary Key is not null.
  /// Call the saveAs() method if you do not want to save it when there is another row with the same account
  /// <returns>Returns BoolResult
  @override
  Future<BoolResult> save({bool ignoreBatch = true}) async {
    final result = BoolResult(success: false);
    try {
      await _mnUser.rawInsert(
          'INSERT ${isSaved! ? 'OR REPLACE' : ''} INTO user (account, userName, motto)  VALUES (?,?,?)',
          toArgsWithIds(),
          ignoreBatch);
      result.success = true;
      isSaved = true;
    } catch (e) {
      result.errorMessage = e.toString();
    }

    saveResult = result;
    return result;
  }

  /// saveAll method saves the sent List<User> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<User> users,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await DbModel().batchStart();
    for (final obj in users) {
      await obj.save();
    }
    if (!isStartedBatch) {
      result = await DbModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns 1
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnUser.rawInsert(
          'INSERT OR REPLACE INTO user (account, userName, motto)  VALUES (?,?,?)',
          [account, userName, motto],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'User account=$account updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'User account=$account did not update');
      }
      return 1;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'User Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// Deletes User

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete User invoked (account=$account)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnUser.delete(
          QueryParams(whereString: 'account=?', whereArguments: [account]));
    } else {
      return _mnUser.updateBatch(
          QueryParams(whereString: 'account=?', whereArguments: [account]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [User] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  UserFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  UserFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      account = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion user

// region UserField
class UserField extends FilterBase {
  UserField(UserFilterBuilder userFB) : super(userFB);

  @override
  UserFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder isNull() {
    return super.isNull() as UserFilterBuilder;
  }

  @override
  UserFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as UserFilterBuilder;
  }

  @override
  UserField get not {
    return super.not as UserField;
  }
}
// endregion UserField

// region UserFilterBuilder
class UserFilterBuilder extends ConjunctionBase {
  UserFilterBuilder(User obj, bool? getIsDeleted) : super(obj, getIsDeleted) {
    _mnUser = obj._mnUser;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  UserManager? _mnUser;

  /// put the sql keyword 'AND'
  @override
  UserFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  UserFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  UserFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  UserFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  UserFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  UserFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  UserFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  UserField _setField(UserField? field, String colName, DbType dbtype) {
    return UserField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  UserField? _account;
  UserField get account {
    return _account = _setField(_account, 'account', DbType.integer);
  }

  UserField? _userName;
  UserField get userName {
    return _userName = _setField(_userName, 'userName', DbType.text);
  }

  UserField? _motto;
  UserField get motto {
    return _motto = _setField(_motto, 'motto', DbType.text);
  }

  /// Deletes List<User> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnUser!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnUser!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'account IN (SELECT account from user ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnUser!.updateBatch(qparams, values);
  }

  /// This method always returns [User] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> User?
  @override
  Future<User?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnUser!.toList(qparams);
    final data = await objFuture;
    User? obj;
    if (data.isNotEmpty) {
      obj = User.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [User]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> User?
  @override
  Future<User> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        User();
  }

  /// This method returns int. [User]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? userCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final usersFuture = await _mnUser!.toList(qparams);
    final int count = usersFuture[0]['CNT'] as int;
    if (userCount != null) {
      userCount(count);
    }
    return count;
  }

  /// This method returns List<User> [User]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<User>
  @override
  Future<List<User>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<User> usersData = await User.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return usersData;
  }

  /// This method returns Json String [User]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [User]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [User]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnUser!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [User]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `account` FROM user WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<String>.
  /// <returns>List<String>
  @override
  Future<List<String>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<String> accountData = <String>[];
    qparams.selectColumns = ['account'];
    final accountFuture = await _mnUser!.toList(qparams);

    final int count = accountFuture.length;
    for (int i = 0; i < count; i++) {
      accountData.add(accountFuture[i]['account'] as String);
    }
    return accountData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [User]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnUser!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await User.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnUser!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion UserFilterBuilder

// region UserFields
class UserFields {
  static TableField? _fAccount;
  static TableField get account {
    return _fAccount =
        _fAccount ?? SqlSyntax.setField(_fAccount, 'account', DbType.integer);
  }

  static TableField? _fUserName;
  static TableField get userName {
    return _fUserName =
        _fUserName ?? SqlSyntax.setField(_fUserName, 'userName', DbType.text);
  }

  static TableField? _fMotto;
  static TableField get motto {
    return _fMotto =
        _fMotto ?? SqlSyntax.setField(_fMotto, 'motto', DbType.text);
  }
}
// endregion UserFields

//region UserManager
class UserManager extends SqfEntityProvider {
  UserManager()
      : super(DbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'user';
  static const List<String> _primaryKeyList = ['account'];
  static const String _whereStr = 'account=?';
}

//endregion UserManager
// region TargetRelation
class TargetRelation extends TableBase {
  TargetRelation(
      {this.activeTargetId,
      this.passiveTargetId,
      this.name,
      this.label,
      this.remark,
      this.typeName,
      this.priority}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  TargetRelation.withFields(this.activeTargetId, this.passiveTargetId,
      this.name, this.label, this.remark, this.typeName, this.priority) {
    _setDefaultValues();
  }
  TargetRelation.withId(this.activeTargetId, this.passiveTargetId, this.name,
      this.label, this.remark, this.typeName, this.priority) {
    _setDefaultValues();
  }
  // fromMap v2.0
  TargetRelation.fromMap(Map<String, dynamic> o,
      {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    if (o['activeTargetId'] != null) {
      activeTargetId = int.tryParse(o['activeTargetId'].toString());
    }
    if (o['passiveTargetId'] != null) {
      passiveTargetId = int.tryParse(o['passiveTargetId'].toString());
    }
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['label'] != null) {
      label = o['label'].toString();
    }
    if (o['remark'] != null) {
      remark = o['remark'].toString();
    }
    if (o['typeName'] != null) {
      typeName = o['typeName'].toString();
    }
    if (o['priority'] != null) {
      priority = int.tryParse(o['priority'].toString());
    }

    isSaved = true;
  }
  // FIELDS (TargetRelation)
  int? activeTargetId;
  int? passiveTargetId;
  String? name;
  String? label;
  String? remark;
  String? typeName;
  int? priority;
  bool? isSaved;
  // end FIELDS (TargetRelation)

  static const bool _softDeleteActivated = false;
  TargetRelationManager? __mnTargetRelation;

  TargetRelationManager get _mnTargetRelation {
    return __mnTargetRelation = __mnTargetRelation ?? TargetRelationManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (activeTargetId != null || !forView) {
      map['activeTargetId'] = activeTargetId;
    }
    if (passiveTargetId != null || !forView) {
      map['passiveTargetId'] = passiveTargetId;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (label != null || !forView) {
      map['label'] = label;
    }
    if (remark != null || !forView) {
      map['remark'] = remark;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (priority != null || !forView) {
      map['priority'] = priority;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (activeTargetId != null || !forView) {
      map['activeTargetId'] = activeTargetId;
    }
    if (passiveTargetId != null || !forView) {
      map['passiveTargetId'] = passiveTargetId;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (label != null || !forView) {
      map['label'] = label;
    }
    if (remark != null || !forView) {
      map['remark'] = remark;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (priority != null || !forView) {
      map['priority'] = priority;
    }

    return map;
  }

  /// This method returns Json String [TargetRelation]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [TargetRelation]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      activeTargetId,
      passiveTargetId,
      name,
      label,
      remark,
      typeName,
      priority
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      activeTargetId,
      passiveTargetId,
      name,
      label,
      remark,
      typeName,
      priority
    ];
  }

  static Future<List<TargetRelation>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR TargetRelation.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<TargetRelation>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <TargetRelation>[];
    try {
      objList = list
          .map((targetrelation) =>
              TargetRelation.fromMap(targetrelation as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR TargetRelation.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<TargetRelation>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<TargetRelation> objList = <TargetRelation>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = TargetRelation.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns TargetRelation by ID if exist, otherwise returns null
  /// Primary Keys: int? activeTargetId, int? passiveTargetId
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [TargetRelation] if exist, otherwise returns null
  Future<TargetRelation?> getById(int? activeTargetId, int? passiveTargetId,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (activeTargetId == null) {
      return null;
    }
    TargetRelation? obj;
    final data =
        await _mnTargetRelation.getById([activeTargetId, passiveTargetId]);
    if (data.length != 0) {
      obj = TargetRelation.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (TargetRelation) object. If the Primary Key (activeTargetId) field is null, returns Error.
  /// INSERTS (If not exist) OR REPLACES (If exist) data while Primary Key is not null.
  /// Call the saveAs() method if you do not want to save it when there is another row with the same activeTargetId
  /// <returns>Returns BoolResult
  @override
  Future<BoolResult> save({bool ignoreBatch = true}) async {
    final result = BoolResult(success: false);
    try {
      await _mnTargetRelation.rawInsert(
          'INSERT ${isSaved! ? 'OR REPLACE' : ''} INTO targetRelation ( activeTargetId, passiveTargetId, name, label, remark, typeName, priority)  VALUES (?,?,?,?,?,?,?)',
          toArgsWithIds(),
          ignoreBatch);
      result.success = true;
      isSaved = true;
    } catch (e) {
      result.errorMessage = e.toString();
    }

    saveResult = result;
    return result;
  }

  /// saveAll method saves the sent List<TargetRelation> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<TargetRelation> targetrelations,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await DbModel().batchStart();
    for (final obj in targetrelations) {
      await obj.save();
    }
    if (!isStartedBatch) {
      result = await DbModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < targetrelations.length; i++) {
        if (targetrelations[i].activeTargetId == null) {
          targetrelations[i].activeTargetId = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns activeTargetId
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnTargetRelation.rawInsert(
          'INSERT OR REPLACE INTO targetRelation ( activeTargetId, passiveTargetId, name, label, remark, typeName, priority)  VALUES (?,?,?,?,?,?,?)',
          [
            activeTargetId,
            passiveTargetId,
            name,
            label,
            remark,
            typeName,
            priority
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage:
                'TargetRelation activeTargetId=$activeTargetId updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage:
                'TargetRelation activeTargetId=$activeTargetId did not update');
      }
      return activeTargetId;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'TargetRelation Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<TargetRelation>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<TargetRelation> targetrelations,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnTargetRelation.rawInsertAll(
        'INSERT OR REPLACE INTO targetRelation ( activeTargetId, passiveTargetId, name, label, remark, typeName, priority)  VALUES (?,?,?,?,?,?,?)',
        targetrelations,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes TargetRelation

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint(
        'SQFENTITIY: delete TargetRelation invoked (activeTargetId=$activeTargetId)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnTargetRelation.delete(QueryParams(
          whereString: 'activeTargetId=? AND passiveTargetId=?',
          whereArguments: [activeTargetId, passiveTargetId]));
    } else {
      return _mnTargetRelation.updateBatch(
          QueryParams(
              whereString: 'activeTargetId=? AND passiveTargetId=?',
              whereArguments: [activeTargetId, passiveTargetId]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [TargetRelation] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  TargetRelationFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TargetRelationFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  TargetRelationFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TargetRelationFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      activeTargetId = null;
      passiveTargetId = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion targetrelation

// region TargetRelationField
class TargetRelationField extends FilterBase {
  TargetRelationField(TargetRelationFilterBuilder targetrelationFB)
      : super(targetrelationFB);

  @override
  TargetRelationFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder isNull() {
    return super.isNull() as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as TargetRelationFilterBuilder;
  }

  @override
  TargetRelationField get not {
    return super.not as TargetRelationField;
  }
}
// endregion TargetRelationField

// region TargetRelationFilterBuilder
class TargetRelationFilterBuilder extends ConjunctionBase {
  TargetRelationFilterBuilder(TargetRelation obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnTargetRelation = obj._mnTargetRelation;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  TargetRelationManager? _mnTargetRelation;

  /// put the sql keyword 'AND'
  @override
  TargetRelationFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  TargetRelationFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  TargetRelationFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  TargetRelationFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  TargetRelationFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  TargetRelationFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  TargetRelationFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TargetRelationFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TargetRelationFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TargetRelationFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TargetRelationFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  TargetRelationField _setField(
      TargetRelationField? field, String colName, DbType dbtype) {
    return TargetRelationField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  TargetRelationField? _activeTargetId;
  TargetRelationField get activeTargetId {
    return _activeTargetId =
        _setField(_activeTargetId, 'activeTargetId', DbType.integer);
  }

  TargetRelationField? _passiveTargetId;
  TargetRelationField get passiveTargetId {
    return _passiveTargetId =
        _setField(_passiveTargetId, 'passiveTargetId', DbType.integer);
  }

  TargetRelationField? _name;
  TargetRelationField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  TargetRelationField? _label;
  TargetRelationField get label {
    return _label = _setField(_label, 'label', DbType.text);
  }

  TargetRelationField? _remark;
  TargetRelationField get remark {
    return _remark = _setField(_remark, 'remark', DbType.text);
  }

  TargetRelationField? _typeName;
  TargetRelationField get typeName {
    return _typeName = _setField(_typeName, 'typeName', DbType.text);
  }

  TargetRelationField? _priority;
  TargetRelationField get priority {
    return _priority = _setField(_priority, 'priority', DbType.integer);
  }

  /// Deletes List<TargetRelation> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnTargetRelation!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnTargetRelation!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'activeTargetId IN (SELECT activeTargetId from targetRelation ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnTargetRelation!.updateBatch(qparams, values);
  }

  /// This method always returns [TargetRelation] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> TargetRelation?
  @override
  Future<TargetRelation?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnTargetRelation!.toList(qparams);
    final data = await objFuture;
    TargetRelation? obj;
    if (data.isNotEmpty) {
      obj = TargetRelation.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [TargetRelation]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> TargetRelation?
  @override
  Future<TargetRelation> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        TargetRelation();
  }

  /// This method returns int. [TargetRelation]
  /// <returns>int
  @override
  Future<int> toCount(
      [VoidCallback Function(int c)? targetrelationCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final targetrelationsFuture = await _mnTargetRelation!.toList(qparams);
    final int count = targetrelationsFuture[0]['CNT'] as int;
    if (targetrelationCount != null) {
      targetrelationCount(count);
    }
    return count;
  }

  /// This method returns List<TargetRelation> [TargetRelation]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<TargetRelation>
  @override
  Future<List<TargetRelation>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<TargetRelation> targetrelationsData =
        await TargetRelation.fromMapList(data,
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields,
            setDefaultValues: qparams.selectColumns == null);
    return targetrelationsData;
  }

  /// This method returns Json String [TargetRelation]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [TargetRelation]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [TargetRelation]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnTargetRelation!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [TargetRelation]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] =
        'SELECT `activeTargetId`passiveTargetId` FROM targetRelation WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<activeTargetId,passiveTargetId> [TargetRelation]
  /// <returns>List<activeTargetId,passiveTargetId>
  @override
  Future<List<TargetRelation>> toListPrimaryKey(
      [bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    qparams.selectColumns = ['activeTargetId', 'passiveTargetId'];
    final targetrelationFuture = await _mnTargetRelation!.toList(qparams);
    return await TargetRelation.fromMapList(targetrelationFuture);
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [TargetRelation]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnTargetRelation!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await TargetRelation.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnTargetRelation!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion TargetRelationFilterBuilder

// region TargetRelationFields
class TargetRelationFields {
  static TableField? _fActiveTargetId;
  static TableField get activeTargetId {
    return _fActiveTargetId = _fActiveTargetId ??
        SqlSyntax.setField(_fActiveTargetId, 'activeTargetId', DbType.integer);
  }

  static TableField? _fPassiveTargetId;
  static TableField get passiveTargetId {
    return _fPassiveTargetId = _fPassiveTargetId ??
        SqlSyntax.setField(
            _fPassiveTargetId, 'passiveTargetId', DbType.integer);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fLabel;
  static TableField get label {
    return _fLabel =
        _fLabel ?? SqlSyntax.setField(_fLabel, 'label', DbType.text);
  }

  static TableField? _fRemark;
  static TableField get remark {
    return _fRemark =
        _fRemark ?? SqlSyntax.setField(_fRemark, 'remark', DbType.text);
  }

  static TableField? _fTypeName;
  static TableField get typeName {
    return _fTypeName =
        _fTypeName ?? SqlSyntax.setField(_fTypeName, 'typeName', DbType.text);
  }

  static TableField? _fPriority;
  static TableField get priority {
    return _fPriority = _fPriority ??
        SqlSyntax.setField(_fPriority, 'priority', DbType.integer);
  }
}
// endregion TargetRelationFields

//region TargetRelationManager
class TargetRelationManager extends SqfEntityProvider {
  TargetRelationManager()
      : super(DbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'targetRelation';
  static const List<String> _primaryKeyList = [
    'activeTargetId',
    'passiveTargetId'
  ];
  static const String _whereStr = 'activeTargetId=? AND passiveTargetId=?';
}

//endregion TargetRelationManager
// region Target
class Target extends TableBase {
  Target(
      {this.id,
      this.code,
      this.name,
      this.typeName,
      this.belongId,
      this.thingId}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Target.withFields(this.id, this.code, this.name, this.typeName, this.belongId,
      this.thingId) {
    _setDefaultValues();
  }
  Target.withId(this.id, this.code, this.name, this.typeName, this.belongId,
      this.thingId) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Target.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['code'] != null) {
      code = o['code'].toString();
    }
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['typeName'] != null) {
      typeName = o['typeName'].toString();
    }
    if (o['belongId'] != null) {
      belongId = int.tryParse(o['belongId'].toString());
    }
    if (o['thingId'] != null) {
      thingId = int.tryParse(o['thingId'].toString());
    }

    isSaved = true;
  }
  // FIELDS (Target)
  int? id;
  String? code;
  String? name;
  String? typeName;
  int? belongId;
  int? thingId;
  bool? isSaved;
  // end FIELDS (Target)

  static const bool _softDeleteActivated = false;
  TargetManager? __mnTarget;

  TargetManager get _mnTarget {
    return __mnTarget = __mnTarget ?? TargetManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (code != null || !forView) {
      map['code'] = code;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (belongId != null || !forView) {
      map['belongId'] = belongId;
    }
    if (thingId != null || !forView) {
      map['thingId'] = thingId;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (code != null || !forView) {
      map['code'] = code;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (belongId != null || !forView) {
      map['belongId'] = belongId;
    }
    if (thingId != null || !forView) {
      map['thingId'] = thingId;
    }

    return map;
  }

  /// This method returns Json String [Target]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Target]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [id, code, name, typeName, belongId, thingId];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [id, code, name, typeName, belongId, thingId];
  }

  static Future<List<Target>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Target.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Target>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Target>[];
    try {
      objList = list
          .map((target) => Target.fromMap(target as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Target.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Target>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Target> objList = <Target>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Target.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Target by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Target] if exist, otherwise returns null
  Future<Target?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    Target? obj;
    final data = await _mnTarget.getById([id]);
    if (data.length != 0) {
      obj = Target.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Target) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0 || !isSaved!) {
      await _mnTarget.insert(this, ignoreBatch);
      if (saveResult!.success) {
        isSaved = true;
      }
    } else {
      await _mnTarget.update(this);
    }

    return id;
  }

  /// Saves the (Target) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0 || !isSaved!) {
      await _mnTarget.insertOrThrow(this, ignoreBatch);
      if (saveResult != null && saveResult!.success) {
        isSaved = true;
      }
      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnTarget.updateOrThrow(this);
    }

    return id;
  }

  /// saveAll method saves the sent List<Target> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Target> targets,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await DbModel().batchStart();
    for (final obj in targets) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await DbModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnTarget.rawInsert(
          'INSERT OR REPLACE INTO target (id, code, name, typeName, belongId, thingId)  VALUES (?,?,?,?,?,?)',
          [id, code, name, typeName, belongId, thingId],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Target id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Target id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Target Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Target>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Target> targets,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnTarget.rawInsertAll(
        'INSERT OR REPLACE INTO target (id, code, name, typeName, belongId, thingId)  VALUES (?,?,?,?,?,?)',
        targets,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Target

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Target invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnTarget
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnTarget.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Target] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  TargetFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TargetFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  TargetFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TargetFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion target

// region TargetField
class TargetField extends FilterBase {
  TargetField(TargetFilterBuilder targetFB) : super(targetFB);

  @override
  TargetFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder isNull() {
    return super.isNull() as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as TargetFilterBuilder;
  }

  @override
  TargetField get not {
    return super.not as TargetField;
  }
}
// endregion TargetField

// region TargetFilterBuilder
class TargetFilterBuilder extends ConjunctionBase {
  TargetFilterBuilder(Target obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnTarget = obj._mnTarget;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  TargetManager? _mnTarget;

  /// put the sql keyword 'AND'
  @override
  TargetFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  TargetFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  TargetFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  TargetFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  TargetFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  TargetFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  TargetFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TargetFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TargetFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TargetFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TargetFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  TargetField _setField(TargetField? field, String colName, DbType dbtype) {
    return TargetField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  TargetField? _id;
  TargetField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  TargetField? _code;
  TargetField get code {
    return _code = _setField(_code, 'code', DbType.text);
  }

  TargetField? _name;
  TargetField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  TargetField? _typeName;
  TargetField get typeName {
    return _typeName = _setField(_typeName, 'typeName', DbType.text);
  }

  TargetField? _belongId;
  TargetField get belongId {
    return _belongId = _setField(_belongId, 'belongId', DbType.integer);
  }

  TargetField? _thingId;
  TargetField get thingId {
    return _thingId = _setField(_thingId, 'thingId', DbType.integer);
  }

  /// Deletes List<Target> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnTarget!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnTarget!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from target ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnTarget!.updateBatch(qparams, values);
  }

  /// This method always returns [Target] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Target?
  @override
  Future<Target?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnTarget!.toList(qparams);
    final data = await objFuture;
    Target? obj;
    if (data.isNotEmpty) {
      obj = Target.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Target]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Target?
  @override
  Future<Target> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Target();
  }

  /// This method returns int. [Target]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? targetCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final targetsFuture = await _mnTarget!.toList(qparams);
    final int count = targetsFuture[0]['CNT'] as int;
    if (targetCount != null) {
      targetCount(count);
    }
    return count;
  }

  /// This method returns List<Target> [Target]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Target>
  @override
  Future<List<Target>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Target> targetsData = await Target.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return targetsData;
  }

  /// This method returns Json String [Target]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Target]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Target]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnTarget!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Target]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM target WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnTarget!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Target]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnTarget!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Target.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnTarget!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion TargetFilterBuilder

// region TargetFields
class TargetFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fCode;
  static TableField get code {
    return _fCode = _fCode ?? SqlSyntax.setField(_fCode, 'code', DbType.text);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fTypeName;
  static TableField get typeName {
    return _fTypeName =
        _fTypeName ?? SqlSyntax.setField(_fTypeName, 'typeName', DbType.text);
  }

  static TableField? _fBelongId;
  static TableField get belongId {
    return _fBelongId = _fBelongId ??
        SqlSyntax.setField(_fBelongId, 'belongId', DbType.integer);
  }

  static TableField? _fThingId;
  static TableField get thingId {
    return _fThingId =
        _fThingId ?? SqlSyntax.setField(_fThingId, 'thingId', DbType.integer);
  }
}
// endregion TargetFields

//region TargetManager
class TargetManager extends SqfEntityProvider {
  TargetManager()
      : super(DbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'target';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion TargetManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await DbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await DbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await DbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class DbModelSequenceManager extends SqfEntityProvider {
  DbModelSequenceManager() : super(DbModel());
}
// END OF ENTITIES
