// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'message_item.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:MessageItem.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// MessageItem TABLE
class TableMessageItem extends SqfEntityTableBase {
  TableMessageItem() {
    // declare properties of EntityTable
    tableName = 'messageItem';
    primaryKeyName = 'seqId';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('account', DbType.text),
      SqfEntityFieldBase('id', DbType.integer),
      SqfEntityFieldBase('name', DbType.text),
      SqfEntityFieldBase('label', DbType.text),
      SqfEntityFieldBase('remark', DbType.text),
      SqfEntityFieldBase('typeName', DbType.text),
      SqfEntityFieldBase('msgTime', DbType.datetime,
          minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableMessageItem();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MessageItemModel extends SqfEntityModelProvider {
  MessageItemModel() {
    databaseName = messageItemModel.databaseName;
    password = messageItemModel.password;
    dbVersion = messageItemModel.dbVersion;
    preSaveAction = messageItemModel.preSaveAction;
    logFunction = messageItemModel.logFunction;
    databaseTables = [
      TableMessageItem.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = messageItemModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = messageItemModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region MessageItem
class MessageItem extends TableBase {
  MessageItem(
      {this.seqId,
      this.account,
      this.id,
      this.name,
      this.label,
      this.remark,
      this.typeName,
      this.msgTime}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  MessageItem.withFields(this.account, this.id, this.name, this.label,
      this.remark, this.typeName, this.msgTime) {
    _setDefaultValues();
  }
  MessageItem.withId(this.seqId, this.account, this.id, this.name, this.label,
      this.remark, this.typeName, this.msgTime) {
    _setDefaultValues();
  }
  // fromMap v2.0
  MessageItem.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    seqId = int.tryParse(o['seqId'].toString());
    if (o['account'] != null) {
      account = o['account'].toString();
    }
    if (o['id'] != null) {
      id = int.tryParse(o['id'].toString());
    }
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['label'] != null) {
      label = o['label'].toString();
    }
    if (o['remark'] != null) {
      remark = o['remark'].toString();
    }
    if (o['typeName'] != null) {
      typeName = o['typeName'].toString();
    }
    if (o['msgTime'] != null) {
      msgTime = int.tryParse(o['msgTime'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['msgTime'].toString())!)
          : DateTime.tryParse(o['msgTime'].toString());
    }
  }
  // FIELDS (MessageItem)
  int? seqId;
  String? account;
  int? id;
  String? name;
  String? label;
  String? remark;
  String? typeName;
  DateTime? msgTime;

  // end FIELDS (MessageItem)

  static const bool _softDeleteActivated = false;
  MessageItemManager? __mnMessageItem;

  MessageItemManager get _mnMessageItem {
    return __mnMessageItem = __mnMessageItem ?? MessageItemManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['seqId'] = seqId;
    if (account != null || !forView) {
      map['account'] = account;
    }
    if (id != null || !forView) {
      map['id'] = id;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (label != null || !forView) {
      map['label'] = label;
    }
    if (remark != null || !forView) {
      map['remark'] = remark;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (msgTime != null) {
      map['msgTime'] = forJson
          ? msgTime!.toString()
          : forQuery
              ? msgTime!.millisecondsSinceEpoch
              : msgTime;
    } else if (msgTime != null || !forView) {
      map['msgTime'] = null;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['seqId'] = seqId;
    if (account != null || !forView) {
      map['account'] = account;
    }
    if (id != null || !forView) {
      map['id'] = id;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (label != null || !forView) {
      map['label'] = label;
    }
    if (remark != null || !forView) {
      map['remark'] = remark;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (msgTime != null) {
      map['msgTime'] = forJson
          ? msgTime!.toString()
          : forQuery
              ? msgTime!.millisecondsSinceEpoch
              : msgTime;
    } else if (msgTime != null || !forView) {
      map['msgTime'] = null;
    }

    return map;
  }

  /// This method returns Json String [MessageItem]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [MessageItem]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      account,
      id,
      name,
      label,
      remark,
      typeName,
      msgTime != null ? msgTime!.millisecondsSinceEpoch : null
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      seqId,
      account,
      id,
      name,
      label,
      remark,
      typeName,
      msgTime != null ? msgTime!.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<MessageItem>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR MessageItem.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<MessageItem>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <MessageItem>[];
    try {
      objList = list
          .map((messageitem) =>
              MessageItem.fromMap(messageitem as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR MessageItem.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<MessageItem>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<MessageItem> objList = <MessageItem>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = MessageItem.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns MessageItem by ID if exist, otherwise returns null
  /// Primary Keys: int? seqId
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [MessageItem] if exist, otherwise returns null
  Future<MessageItem?> getById(int? seqId,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (seqId == null) {
      return null;
    }
    MessageItem? obj;
    final data = await _mnMessageItem.getById([seqId]);
    if (data.length != 0) {
      obj = MessageItem.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (MessageItem) object. If the seqId field is null, saves as a new record and returns new seqId, if seqId is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns seqId
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (seqId == null || seqId == 0) {
      seqId = await _mnMessageItem.insert(this, ignoreBatch);
    } else {
      await _mnMessageItem.update(this);
    }

    return seqId;
  }

  /// Saves the (MessageItem) object. If the seqId field is null, saves as a new record and returns new seqId, if seqId is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns seqId
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (seqId == null || seqId == 0) {
      seqId = await _mnMessageItem.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // seqId= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnMessageItem.updateOrThrow(this);
    }

    return seqId;
  }

  /// saveAs MessageItem. Returns a new Primary Key value of MessageItem

  /// <returns>Returns a new Primary Key value of MessageItem
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    seqId = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<MessageItem> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<MessageItem> messageitems,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await MessageItemModel().batchStart();
    for (final obj in messageitems) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await MessageItemModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < messageitems.length; i++) {
        if (messageitems[i].seqId == null) {
          messageitems[i].seqId = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns seqId
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnMessageItem.rawInsert(
          'INSERT OR REPLACE INTO messageItem (seqId, account, id, name, label, remark, typeName, msgTime)  VALUES (?,?,?,?,?,?,?,?)',
          [
            seqId,
            account,
            id,
            name,
            label,
            remark,
            typeName,
            msgTime != null ? msgTime!.millisecondsSinceEpoch : null
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'MessageItem seqId=$seqId updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'MessageItem seqId=$seqId did not update');
      }
      return seqId;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'MessageItem Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<MessageItem>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<MessageItem> messageitems,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnMessageItem.rawInsertAll(
        'INSERT OR REPLACE INTO messageItem (seqId, account, id, name, label, remark, typeName, msgTime)  VALUES (?,?,?,?,?,?,?,?)',
        messageitems,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes MessageItem

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete MessageItem invoked (seqId=$seqId)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnMessageItem
          .delete(QueryParams(whereString: 'seqId=?', whereArguments: [seqId]));
    } else {
      return _mnMessageItem.updateBatch(
          QueryParams(whereString: 'seqId=?', whereArguments: [seqId]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [MessageItem] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  MessageItemFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return MessageItemFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  MessageItemFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return MessageItemFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}

  @override
  void rollbackPk() {
    if (isInsert == true) {
      seqId = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion messageitem

// region MessageItemField
class MessageItemField extends FilterBase {
  MessageItemField(MessageItemFilterBuilder messageitemFB)
      : super(messageitemFB);

  @override
  MessageItemFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder isNull() {
    return super.isNull() as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as MessageItemFilterBuilder;
  }

  @override
  MessageItemField get not {
    return super.not as MessageItemField;
  }
}
// endregion MessageItemField

// region MessageItemFilterBuilder
class MessageItemFilterBuilder extends ConjunctionBase {
  MessageItemFilterBuilder(MessageItem obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnMessageItem = obj._mnMessageItem;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  MessageItemManager? _mnMessageItem;

  /// put the sql keyword 'AND'
  @override
  MessageItemFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  MessageItemFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  MessageItemFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  MessageItemFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  MessageItemFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  MessageItemFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  MessageItemFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  MessageItemFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  MessageItemFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  MessageItemFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  MessageItemFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  MessageItemField _setField(
      MessageItemField? field, String colName, DbType dbtype) {
    return MessageItemField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  MessageItemField? _seqId;
  MessageItemField get seqId {
    return _seqId = _setField(_seqId, 'seqId', DbType.integer);
  }

  MessageItemField? _account;
  MessageItemField get account {
    return _account = _setField(_account, 'account', DbType.text);
  }

  MessageItemField? _id;
  MessageItemField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  MessageItemField? _name;
  MessageItemField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  MessageItemField? _label;
  MessageItemField get label {
    return _label = _setField(_label, 'label', DbType.text);
  }

  MessageItemField? _remark;
  MessageItemField get remark {
    return _remark = _setField(_remark, 'remark', DbType.text);
  }

  MessageItemField? _typeName;
  MessageItemField get typeName {
    return _typeName = _setField(_typeName, 'typeName', DbType.text);
  }

  MessageItemField? _msgTime;
  MessageItemField get msgTime {
    return _msgTime = _setField(_msgTime, 'msgTime', DbType.datetime);
  }

  /// Deletes List<MessageItem> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnMessageItem!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnMessageItem!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'seqId IN (SELECT seqId from messageItem ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnMessageItem!.updateBatch(qparams, values);
  }

  /// This method always returns [MessageItem] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> MessageItem?
  @override
  Future<MessageItem?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnMessageItem!.toList(qparams);
    final data = await objFuture;
    MessageItem? obj;
    if (data.isNotEmpty) {
      obj = MessageItem.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [MessageItem]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> MessageItem?
  @override
  Future<MessageItem> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        MessageItem();
  }

  /// This method returns int. [MessageItem]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? messageitemCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final messageitemsFuture = await _mnMessageItem!.toList(qparams);
    final int count = messageitemsFuture[0]['CNT'] as int;
    if (messageitemCount != null) {
      messageitemCount(count);
    }
    return count;
  }

  /// This method returns List<MessageItem> [MessageItem]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<MessageItem>
  @override
  Future<List<MessageItem>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<MessageItem> messageitemsData = await MessageItem.fromMapList(
        data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return messageitemsData;
  }

  /// This method returns Json String [MessageItem]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [MessageItem]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [MessageItem]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnMessageItem!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [MessageItem]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] =
        'SELECT `seqId` FROM messageItem WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> seqIdData = <int>[];
    qparams.selectColumns = ['seqId'];
    final seqIdFuture = await _mnMessageItem!.toList(qparams);

    final int count = seqIdFuture.length;
    for (int i = 0; i < count; i++) {
      seqIdData.add(seqIdFuture[i]['seqId'] as int);
    }
    return seqIdData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [MessageItem]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnMessageItem!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await MessageItem.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnMessageItem!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion MessageItemFilterBuilder

// region MessageItemFields
class MessageItemFields {
  static TableField? _fSeqId;
  static TableField get seqId {
    return _fSeqId =
        _fSeqId ?? SqlSyntax.setField(_fSeqId, 'seqid', DbType.integer);
  }

  static TableField? _fAccount;
  static TableField get account {
    return _fAccount =
        _fAccount ?? SqlSyntax.setField(_fAccount, 'account', DbType.text);
  }

  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fLabel;
  static TableField get label {
    return _fLabel =
        _fLabel ?? SqlSyntax.setField(_fLabel, 'label', DbType.text);
  }

  static TableField? _fRemark;
  static TableField get remark {
    return _fRemark =
        _fRemark ?? SqlSyntax.setField(_fRemark, 'remark', DbType.text);
  }

  static TableField? _fTypeName;
  static TableField get typeName {
    return _fTypeName =
        _fTypeName ?? SqlSyntax.setField(_fTypeName, 'typeName', DbType.text);
  }

  static TableField? _fMsgTime;
  static TableField get msgTime {
    return _fMsgTime =
        _fMsgTime ?? SqlSyntax.setField(_fMsgTime, 'msgTime', DbType.datetime);
  }
}
// endregion MessageItemFields

//region MessageItemManager
class MessageItemManager extends SqfEntityProvider {
  MessageItemManager()
      : super(MessageItemModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'messageItem';
  static const List<String> _primaryKeyList = ['seqId'];
  static const String _whereStr = 'seqId=?';
}

//endregion MessageItemManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await MessageItemModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await MessageItemModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await MessageItemModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class MessageItemModelSequenceManager extends SqfEntityProvider {
  MessageItemModelSequenceManager() : super(MessageItemModel());
}
// END OF ENTITIES
