// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'target.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Target.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Target TABLE
class TableTarget extends SqfEntityTableBase {
  TableTarget() {
    // declare properties of EntityTable
    tableName = 'target';
    primaryKeyName = 'seqId';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('id', DbType.integer),
      SqfEntityFieldBase('name', DbType.text),
      SqfEntityFieldBase('code', DbType.text),
      SqfEntityFieldBase('typeName', DbType.text),
      SqfEntityFieldBase('thingId', DbType.integer),
      SqfEntityFieldBase('status', DbType.integer),
      SqfEntityFieldBase('createUser', DbType.integer),
      SqfEntityFieldBase('updateUser', DbType.integer),
      SqfEntityFieldBase('version', DbType.integer),
      SqfEntityFieldBase('createTime', DbType.datetime,
          minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('updateTime', DbType.datetime,
          minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableTarget();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class TargetModel extends SqfEntityModelProvider {
  TargetModel() {
    databaseName = targetModel.databaseName;
    password = targetModel.password;
    dbVersion = targetModel.dbVersion;
    preSaveAction = targetModel.preSaveAction;
    logFunction = targetModel.logFunction;
    databaseTables = [
      TableTarget.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = targetModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = targetModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Target
class Target extends TableBase {
  Target(
      {this.seqId,
      this.id,
      this.name,
      this.code,
      this.typeName,
      this.thingId,
      this.status,
      this.createUser,
      this.updateUser,
      this.version,
      this.createTime,
      this.updateTime}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Target.withFields(
      this.id,
      this.name,
      this.code,
      this.typeName,
      this.thingId,
      this.status,
      this.createUser,
      this.updateUser,
      this.version,
      this.createTime,
      this.updateTime) {
    _setDefaultValues();
  }
  Target.withId(
      this.seqId,
      this.id,
      this.name,
      this.code,
      this.typeName,
      this.thingId,
      this.status,
      this.createUser,
      this.updateUser,
      this.version,
      this.createTime,
      this.updateTime) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Target.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    seqId = int.tryParse(o['seqId'].toString());
    if (o['id'] != null) {
      id = int.tryParse(o['id'].toString());
    }
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['code'] != null) {
      code = o['code'].toString();
    }
    if (o['typeName'] != null) {
      typeName = o['typeName'].toString();
    }
    if (o['thingId'] != null) {
      thingId = int.tryParse(o['thingId'].toString());
    }
    if (o['status'] != null) {
      status = int.tryParse(o['status'].toString());
    }
    if (o['createUser'] != null) {
      createUser = int.tryParse(o['createUser'].toString());
    }
    if (o['updateUser'] != null) {
      updateUser = int.tryParse(o['updateUser'].toString());
    }
    if (o['version'] != null) {
      version = int.tryParse(o['version'].toString());
    }
    if (o['createTime'] != null) {
      createTime = int.tryParse(o['createTime'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['createTime'].toString())!)
          : DateTime.tryParse(o['createTime'].toString());
    }
    if (o['updateTime'] != null) {
      updateTime = int.tryParse(o['updateTime'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['updateTime'].toString())!)
          : DateTime.tryParse(o['updateTime'].toString());
    }
  }
  // FIELDS (Target)
  int? seqId;
  int? id;
  String? name;
  String? code;
  String? typeName;
  int? thingId;
  int? status;
  int? createUser;
  int? updateUser;
  int? version;
  DateTime? createTime;
  DateTime? updateTime;

  // end FIELDS (Target)

  static const bool _softDeleteActivated = false;
  TargetManager? __mnTarget;

  TargetManager get _mnTarget {
    return __mnTarget = __mnTarget ?? TargetManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['seqId'] = seqId;
    if (id != null || !forView) {
      map['id'] = id;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (code != null || !forView) {
      map['code'] = code;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (thingId != null || !forView) {
      map['thingId'] = thingId;
    }
    if (status != null || !forView) {
      map['status'] = status;
    }
    if (createUser != null || !forView) {
      map['createUser'] = createUser;
    }
    if (updateUser != null || !forView) {
      map['updateUser'] = updateUser;
    }
    if (version != null || !forView) {
      map['version'] = version;
    }
    if (createTime != null) {
      map['createTime'] = forJson
          ? createTime!.toString()
          : forQuery
              ? createTime!.millisecondsSinceEpoch
              : createTime;
    } else if (createTime != null || !forView) {
      map['createTime'] = null;
    }
    if (updateTime != null) {
      map['updateTime'] = forJson
          ? updateTime!.toString()
          : forQuery
              ? updateTime!.millisecondsSinceEpoch
              : updateTime;
    } else if (updateTime != null || !forView) {
      map['updateTime'] = null;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['seqId'] = seqId;
    if (id != null || !forView) {
      map['id'] = id;
    }
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (code != null || !forView) {
      map['code'] = code;
    }
    if (typeName != null || !forView) {
      map['typeName'] = typeName;
    }
    if (thingId != null || !forView) {
      map['thingId'] = thingId;
    }
    if (status != null || !forView) {
      map['status'] = status;
    }
    if (createUser != null || !forView) {
      map['createUser'] = createUser;
    }
    if (updateUser != null || !forView) {
      map['updateUser'] = updateUser;
    }
    if (version != null || !forView) {
      map['version'] = version;
    }
    if (createTime != null) {
      map['createTime'] = forJson
          ? createTime!.toString()
          : forQuery
              ? createTime!.millisecondsSinceEpoch
              : createTime;
    } else if (createTime != null || !forView) {
      map['createTime'] = null;
    }
    if (updateTime != null) {
      map['updateTime'] = forJson
          ? updateTime!.toString()
          : forQuery
              ? updateTime!.millisecondsSinceEpoch
              : updateTime;
    } else if (updateTime != null || !forView) {
      map['updateTime'] = null;
    }

    return map;
  }

  /// This method returns Json String [Target]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Target]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      id,
      name,
      code,
      typeName,
      thingId,
      status,
      createUser,
      updateUser,
      version,
      createTime != null ? createTime!.millisecondsSinceEpoch : null,
      updateTime != null ? updateTime!.millisecondsSinceEpoch : null
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      seqId,
      id,
      name,
      code,
      typeName,
      thingId,
      status,
      createUser,
      updateUser,
      version,
      createTime != null ? createTime!.millisecondsSinceEpoch : null,
      updateTime != null ? updateTime!.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<Target>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Target.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Target>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Target>[];
    try {
      objList = list
          .map((target) => Target.fromMap(target as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Target.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Target>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Target> objList = <Target>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Target.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Target by ID if exist, otherwise returns null
  /// Primary Keys: int? seqId
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Target] if exist, otherwise returns null
  Future<Target?> getById(int? seqId,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (seqId == null) {
      return null;
    }
    Target? obj;
    final data = await _mnTarget.getById([seqId]);
    if (data.length != 0) {
      obj = Target.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Target) object. If the seqId field is null, saves as a new record and returns new seqId, if seqId is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns seqId
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (seqId == null || seqId == 0) {
      seqId = await _mnTarget.insert(this, ignoreBatch);
    } else {
      await _mnTarget.update(this);
    }

    return seqId;
  }

  /// Saves the (Target) object. If the seqId field is null, saves as a new record and returns new seqId, if seqId is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns seqId
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (seqId == null || seqId == 0) {
      seqId = await _mnTarget.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // seqId= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnTarget.updateOrThrow(this);
    }

    return seqId;
  }

  /// saveAs Target. Returns a new Primary Key value of Target

  /// <returns>Returns a new Primary Key value of Target
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    seqId = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<Target> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Target> targets,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await TargetModel().batchStart();
    for (final obj in targets) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await TargetModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < targets.length; i++) {
        if (targets[i].seqId == null) {
          targets[i].seqId = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns seqId
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnTarget.rawInsert(
          'INSERT OR REPLACE INTO target (seqId, id, name, code, typeName, thingId, status, createUser, updateUser, version, createTime, updateTime)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',
          [
            seqId,
            id,
            name,
            code,
            typeName,
            thingId,
            status,
            createUser,
            updateUser,
            version,
            createTime != null ? createTime!.millisecondsSinceEpoch : null,
            updateTime != null ? updateTime!.millisecondsSinceEpoch : null
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Target seqId=$seqId updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Target seqId=$seqId did not update');
      }
      return seqId;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Target Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Target>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Target> targets,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnTarget.rawInsertAll(
        'INSERT OR REPLACE INTO target (seqId, id, name, code, typeName, thingId, status, createUser, updateUser, version, createTime, updateTime)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',
        targets,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Target

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Target invoked (seqId=$seqId)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnTarget
          .delete(QueryParams(whereString: 'seqId=?', whereArguments: [seqId]));
    } else {
      return _mnTarget.updateBatch(
          QueryParams(whereString: 'seqId=?', whereArguments: [seqId]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Target] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  TargetFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TargetFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  TargetFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return TargetFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}

  @override
  void rollbackPk() {
    if (isInsert == true) {
      seqId = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion target

// region TargetField
class TargetField extends FilterBase {
  TargetField(TargetFilterBuilder targetFB) : super(targetFB);

  @override
  TargetFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder isNull() {
    return super.isNull() as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as TargetFilterBuilder;
  }

  @override
  TargetFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as TargetFilterBuilder;
  }

  @override
  TargetField get not {
    return super.not as TargetField;
  }
}
// endregion TargetField

// region TargetFilterBuilder
class TargetFilterBuilder extends ConjunctionBase {
  TargetFilterBuilder(Target obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnTarget = obj._mnTarget;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  TargetManager? _mnTarget;

  /// put the sql keyword 'AND'
  @override
  TargetFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  TargetFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  TargetFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  TargetFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  TargetFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  TargetFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  TargetFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TargetFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TargetFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  TargetFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  TargetFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  TargetField _setField(TargetField? field, String colName, DbType dbtype) {
    return TargetField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  TargetField? _seqId;
  TargetField get seqId {
    return _seqId = _setField(_seqId, 'seqId', DbType.integer);
  }

  TargetField? _id;
  TargetField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  TargetField? _name;
  TargetField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  TargetField? _code;
  TargetField get code {
    return _code = _setField(_code, 'code', DbType.text);
  }

  TargetField? _typeName;
  TargetField get typeName {
    return _typeName = _setField(_typeName, 'typeName', DbType.text);
  }

  TargetField? _thingId;
  TargetField get thingId {
    return _thingId = _setField(_thingId, 'thingId', DbType.integer);
  }

  TargetField? _status;
  TargetField get status {
    return _status = _setField(_status, 'status', DbType.integer);
  }

  TargetField? _createUser;
  TargetField get createUser {
    return _createUser = _setField(_createUser, 'createUser', DbType.integer);
  }

  TargetField? _updateUser;
  TargetField get updateUser {
    return _updateUser = _setField(_updateUser, 'updateUser', DbType.integer);
  }

  TargetField? _version;
  TargetField get version {
    return _version = _setField(_version, 'version', DbType.integer);
  }

  TargetField? _createTime;
  TargetField get createTime {
    return _createTime = _setField(_createTime, 'createTime', DbType.datetime);
  }

  TargetField? _updateTime;
  TargetField get updateTime {
    return _updateTime = _setField(_updateTime, 'updateTime', DbType.datetime);
  }

  /// Deletes List<Target> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnTarget!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnTarget!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'seqId IN (SELECT seqId from target ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnTarget!.updateBatch(qparams, values);
  }

  /// This method always returns [Target] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Target?
  @override
  Future<Target?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnTarget!.toList(qparams);
    final data = await objFuture;
    Target? obj;
    if (data.isNotEmpty) {
      obj = Target.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Target]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Target?
  @override
  Future<Target> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Target();
  }

  /// This method returns int. [Target]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? targetCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final targetsFuture = await _mnTarget!.toList(qparams);
    final int count = targetsFuture[0]['CNT'] as int;
    if (targetCount != null) {
      targetCount(count);
    }
    return count;
  }

  /// This method returns List<Target> [Target]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Target>
  @override
  Future<List<Target>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Target> targetsData = await Target.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return targetsData;
  }

  /// This method returns Json String [Target]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Target]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Target]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnTarget!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Target]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `seqId` FROM target WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> seqIdData = <int>[];
    qparams.selectColumns = ['seqId'];
    final seqIdFuture = await _mnTarget!.toList(qparams);

    final int count = seqIdFuture.length;
    for (int i = 0; i < count; i++) {
      seqIdData.add(seqIdFuture[i]['seqId'] as int);
    }
    return seqIdData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Target]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnTarget!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Target.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnTarget!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion TargetFilterBuilder

// region TargetFields
class TargetFields {
  static TableField? _fSeqId;
  static TableField get seqId {
    return _fSeqId =
        _fSeqId ?? SqlSyntax.setField(_fSeqId, 'seqid', DbType.integer);
  }

  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fCode;
  static TableField get code {
    return _fCode = _fCode ?? SqlSyntax.setField(_fCode, 'code', DbType.text);
  }

  static TableField? _fTypeName;
  static TableField get typeName {
    return _fTypeName =
        _fTypeName ?? SqlSyntax.setField(_fTypeName, 'typeName', DbType.text);
  }

  static TableField? _fThingId;
  static TableField get thingId {
    return _fThingId =
        _fThingId ?? SqlSyntax.setField(_fThingId, 'thingId', DbType.integer);
  }

  static TableField? _fStatus;
  static TableField get status {
    return _fStatus =
        _fStatus ?? SqlSyntax.setField(_fStatus, 'status', DbType.integer);
  }

  static TableField? _fCreateUser;
  static TableField get createUser {
    return _fCreateUser = _fCreateUser ??
        SqlSyntax.setField(_fCreateUser, 'createUser', DbType.integer);
  }

  static TableField? _fUpdateUser;
  static TableField get updateUser {
    return _fUpdateUser = _fUpdateUser ??
        SqlSyntax.setField(_fUpdateUser, 'updateUser', DbType.integer);
  }

  static TableField? _fVersion;
  static TableField get version {
    return _fVersion =
        _fVersion ?? SqlSyntax.setField(_fVersion, 'version', DbType.integer);
  }

  static TableField? _fCreateTime;
  static TableField get createTime {
    return _fCreateTime = _fCreateTime ??
        SqlSyntax.setField(_fCreateTime, 'createTime', DbType.datetime);
  }

  static TableField? _fUpdateTime;
  static TableField get updateTime {
    return _fUpdateTime = _fUpdateTime ??
        SqlSyntax.setField(_fUpdateTime, 'updateTime', DbType.datetime);
  }
}
// endregion TargetFields

//region TargetManager
class TargetManager extends SqfEntityProvider {
  TargetManager()
      : super(TargetModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'target';
  static const List<String> _primaryKeyList = ['seqId'];
  static const String _whereStr = 'seqId=?';
}

//endregion TargetManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await TargetModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await TargetModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await TargetModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class TargetModelSequenceManager extends SqfEntityProvider {
  TargetModelSequenceManager() : super(TargetModel());
}
// END OF ENTITIES
